### ISSUE TITLE
Calendar choice for long time period data set 

### ISSUE THREAD

**Issue by beusena** [cf-convention/discuss#52]
I am working on converting the output of the History Database of the Global Environment (HYDE) into netcdf.
I have a time period of 10000 BCE upto the year 2100.

This is a time period that does not fit in the four character representation of the years. Also num2date and date2num does not support negative years.
 
My question:
Is there a way to get all these years into one netcdf file? What would be the calendar definition and the reference time?

**Comment by sethmcg** [comment]
If you use num2date and date2num from the cftime module, it supports negative times and all the CF calendars.  I don't know with certainty that it supports 5-digit years, but I'd be surprised if it didn't.

With negative time value support, you're free to choose whatever reference time is most convenient.  If you're inputting Julian dates before 1582 and Gregorian dates after, the calendar attribute is "standard"; otherwise, you probably want to use a "proleptic_gregorian" calendar to extend the Gregorian calendar backwards.

**Comment by beusena** [comment]
Thank you for your comment.

I tried the following code:
import cftime

time_unit = 'days since 1-1-1 0:0:0'
calendar = 'proleptic_gregorian'

t0 = cftime.date2num(cftime.datetime(100,1,1),time_unit,calendar)
print(t0)
t1 = cftime.date2num(cftime.datetime(-100,1,1),time_unit,calendar)
print(t1)

The output of this program:
36159.0
Traceback (most recent call last):
  File "timetest.py", line 8, in <module>
    t1 = cftime.date2num(cftime.datetime(-100,1,1),time_unit,calendar)
  File "cftime/_cftime.pyx", line 226, in cftime._cftime.date2num
  File "cftime/_cftime.pyx", line 1437, in cftime._cftime.datetime.__sub__
  File "cftime/_cftime.pyx", line 1319, in cftime._cftime.datetime._to_real_datetime
ValueError: year -100 is out of range

I am using python 3.7 within anaconda.
The cftime module:
cftime                    1.1.1.2          py36h035aef0_0 

So my conclusion is that the cftime module does not support negative years. Also specifying the time_unit before 1-1-1 is not possible (at least i don't know how).

Are there other ways?

**Comment by JimBiardCics** [comment]
@beusena This looks like it may be a flaw in cftime. I tried the code below: 
```
import netCDF4

a = netCDF4.num2date([-100000000], 'days since 1-1-1', calendar = '365_day')
print(a)
```
which produces the result
```
[cftime.DatetimeNoLeap(-273972-05-26 00:00:00)]
```
But if I try
```
a = netCDF4.num2date([-100000000], 'days since 1-1-1', calendar = 'proleptic_gregorian')
``` 
I get a ValueError exception stating
```
ValueError: julian day must be a positive integer
```
It isn't a wonderful solution, but if your data is granularity is in terms of years, you could use the 365_day calendar. Another workaround solution is to set the units of your time variable to 'years' without any epoch information and simply store the year number. This may cause some software to have heartburn. You could explain the exact meaning of your variable in a comment attribute.

**Comment by JimBiardCics** [comment]
@beusena Another thing. A time variable of the form:
```
double time(time);
    :units = "days since 1-1-1";
    :calendar = "proleptic_gregorian";
    :standard_name = "time";
    :axis = "T";
```
is completely valid CF. The fact that cftime as a software package throws an error is a problem with cftime.

**Comment by sethmcg** [comment]
@buesena Given the limitations of date2num in the numpy and cftime libraries, you may need to convert your dates by hand.  It's a little tricky, but not too bad; I think the main pitfalls are getting the rules for leap years correct and being sure whether your input dates use year zero.  I've found the Wikipedia page for the Gregorian calendar to be pretty clear.

**Comment by beusena** [comment]
Thank you for your suggestions.

I solved this problem with a combination of the two suggestions.

First the date2num issue. I solved that by suggestion of sethmcg to write my own conversion. I choose to use the 365_day calendar, which makes life easier, because I only have annual data.
So this is my settings:

time_unit = 'days since 1-1-1 00:00:00'
calendar = '365_day'

def convert_year2num(year):
    '''
    Convert HYDE year into a number of years since 1-1-1.
    '''
    return (year - 1) * 365

I checked the new netcdf file with cdo, ncview and panoply (and of course python) and it works fine.

The only thing that remains is the date of the year.
What is the convention on annual data:
1 January or 15 July or 31 December? Or is it a free choice?

Once again, thanks for your help!

**Comment by sethmcg** [comment]
It's a free choice.  I think it's best to put the time coordinate in the middle of the interval.  If you put it at the beginning or the end, you have to remember which it was and it's possible to get confused, but if you put it in the middle, it's always clear.

Glad to hear you were able to get a solution working!
